import { PhaseGroupType } from "./@types/types";

const OUTPUT_PATH = "C:/data";

export const LEGENDS = new Map<string, string>(require("../data/legends.json"));
export const LEGEND_NAMES = require("../data/legendsNames.json");

export const COUNTRIES = [
  "Unknown",
  "United States",
  "Canada",
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "DR Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "England",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "European Union",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern and Antarctic Lands",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islands",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "São Tomé and Príncipe",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States Minor Outlying Islands",
  "United States Virgin Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wales",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const IMAGES = {
  sponsor: "img/sponsor.png",
  blank: "img/blank.png",
  winner: "img/bracketwinner.png",
  default: "img/bracketdefault.png",
  winnerOpacity: "img/opacity/Winner.png",
  loserOpacity: "img/opacity/Loser.png",
  crown: "img/crown.mov",
  twitter: "img/twitter.png",
};

export const SLUG_TO_REGION = new Map([
  ["australia", "Australia"],
  ["europe", "Europe"],
  ["north-america", "North America"],
  ["south-america", "South America"],
  ["southeast-asia", "Southeast Asia"],
]);

export const SGG_SELECTION_TO_LEGEND = new Map([
  ["156", "ADA"],
  ["157", "ASURI"],
  ["158", "AZOTH"],
  ["159", "BARRAZA"],
  ["160", "BODVAR"],
  ["161", "BRYNN"],
  ["162", "CASSIDY"],
  ["163", "DIANA"],
  ["164", "EMBER"],
  ["165", "GNASH"],
  ["166", "HATTORI"],
  ["167", "JHALA"],
  ["168", "KOJI"],
  ["169", "LORD_VRAXX"],
  ["170", "LUCIEN"],
  ["171", "ORION"],
  ["172", "QUEEN_NAI"],
  ["173", "SIR_ROLAND"],
  ["174", "SCARLET"],
  ["175", "SENTINEL"],
  ["176", "TEROS"],
  ["177", "THATCH"],
  ["178", "ULGRIM"],
  ["179", "KOR"],
  ["530", "WU_SHANG"],
  ["531", "VAL"],
  ["532", "RAGNIR"],
  ["533", "CROSS"],
  ["535", "MIRAGE"],
  ["627", "NIX"],
  ["688", "MORDEX"],
  ["794", "YUMIKO"],
  ["847", "CASPIAN"],
  ["1160", "ARTEMIS"],
  ["1161", "KAYA"],
  ["1162", "XULL"],
  ["1163", "SIDRA"],
  ["1445", "ISAIAH"],
  ["1446", "JIRO"],
  ["1447", "LIN_FEI"],
  ["1448", "ZARIEL"],
  ["1449", "RAYMAN"],
  ["1450", "DUSK"],
  ["1451", "FAIT"],
  ["1455", "THOR"],
  ["1494", "JHALA"], // Finn
  ["1495", "KOR"], // Jake
  ["1496", "LORD_VRAXX"], // Princess Bubblegum
  ["1525", "PETRA"],
  ["1540", "VOLKOV"],
  ["1714", "VECTOR"],
  ["1715", "ONYX"],
  ["1764", "MAKO"],
  ["1824", "MAGYAR"],
  ["1824", "RENO"],
  ["1918", "MUNIN"],
  ["2051", "EZIO"],
  ["2052", "ARCADIA"],
  ["2120", "TEZCA"],
  ["2304", "THEA"],
  ["2309", "RED_RAPTOR"],
]);

export const LEGEND_RENDER_OFFSETS: {
  [legend: string]: { offsetX: number; offsetZ: number };
} = {
  AANG: { offsetX: -106, offsetZ: -26 },
  ADA: { offsetX: -14, offsetZ: 166 },
  AKUMA: { offsetX: -74, offsetZ: 148 },
  AKUMA_NO_KOGO_HATTORI: { offsetX: -102, offsetZ: 227 },
  ALUCARD: { offsetX: -2, offsetZ: 36 },
  AMYTHEST: { offsetX: -110, offsetZ: 188 },
  ARCADIA: { offsetX: -142, offsetZ: 0 },
  ARTEMIS: { offsetX: -116, offsetZ: 50 },
  ASUKA: { offsetX: 0, offsetZ: 48 },
  ASURI: { offsetX: 29, offsetZ: 188 },
  AURORA_BRYNN: { offsetX: -40, offsetZ: -78 },
  AZOTH: { offsetX: -81, offsetZ: 71 },
  BARBARA: { offsetX: -67, offsetZ: 102 },
  BARRAZA: { offsetX: -108, offsetZ: 62 },
  BECKY_LYNCH: { offsetX: 24, offsetZ: -83 },
  BLACK_KNIGHT: { offsetX: -16, offsetZ: 0 },
  BODVAR: { offsetX: -142, offsetZ: 98 },
  BRYNN: { offsetX: -98, offsetZ: 21 },
  CASPIAN: { offsetX: 0, offsetZ: 69 },
  CASSIDY: { offsetX: -104, offsetZ: 156 },
  CHEL: { offsetX: -270, offsetZ: 180 },
  CHUN_LI: { offsetX: -104, offsetZ: 56 },
  CROSS: { offsetX: -86, offsetZ: 96 },
  DAIMIO: { offsetX: -288, offsetZ: 244 },
  DARYL: { offsetX: 0, offsetZ: 30 },
  DHALSIM: { offsetX: -54, offsetZ: 94 },
  DIAMONDHEAD: { offsetX: -29, offsetZ: 104 },
  DIANA: { offsetX: -142, offsetZ: 72 },
  DONATELLO: { offsetX: 0, offsetZ: 18 },
  DUSK: { offsetX: 144, offsetZ: 206 },
  EIVOR: { offsetX: -98, offsetZ: 91 },
  EMBER: { offsetX: 22, offsetZ: 212 },
  ENCHANTRESS: { offsetX: -34, offsetZ: -30 },
  EZIO: { offsetX: -110, offsetZ: 60 },
  FAIT: { offsetX: 102, offsetZ: 70 },
  FANGWILDS_HEART_EMBER: { offsetX: -18, offsetZ: 88 },
  FINN: { offsetX: 0, offsetZ: 60 },
  FOUR_ARMS: { offsetX: -18, offsetZ: -16 },
  GARNET: { offsetX: -14, offsetZ: 40 },
  GLOBOX: { offsetX: 58, offsetZ: 124 },
  GNASH: { offsetX: -54, offsetZ: 192 },
  GRUAGACH: { offsetX: -80, offsetZ: 58 },
  HATTORI: { offsetX: -52, offsetZ: 228 },
  HEATBLAST: { offsetX: 12, offsetZ: 60 },
  HELLBOY: { offsetX: -180, offsetZ: 58 },
  HUGIN: { offsetX: -30, offsetZ: 24 },
  INFERNAL_WARLOCK_VOLKOV: { offsetX: -82, offsetZ: -18 },
  ISAIAH: { offsetX: -172, offsetZ: 224 },
  JAEYUN: { offsetX: -42, offsetZ: 24 },
  JAKE: { offsetX: -138, offsetZ: 122 },
  JHALA: { offsetX: 30, offsetZ: 100 },
  JIRO: { offsetX: -36, offsetZ: 230 },
  JOHN_CENA: { offsetX: -34, offsetZ: 18 },
  KAYA: { offsetX: -18, offsetZ: 116 },
  KEN: { offsetX: -12, offsetZ: 2 },
  KING_KNIGHT: { offsetX: -46, offsetZ: 68 },
  KOJI: { offsetX: -154, offsetZ: 170 },
  KOR: { offsetX: -12, offsetZ: 78 },
  LARA_CROFT: { offsetX: 36, offsetZ: 68 },
  LEONARDO: { offsetX: 28, offsetZ: 0 },
  LIN_FEI: { offsetX: -61, offsetZ: 194 },
  LORD_VRAXX: { offsetX: -142, offsetZ: 132 },
  LUCIEN: { offsetX: -38, offsetZ: 96 },
  LUKE: { offsetX: -96, offsetZ: 52 },
  M_BISON: { offsetX: 8, offsetZ: -72 },
  MACHO_MAN: { offsetX: -45, offsetZ: 5 },
  MAGGIE: { offsetX: -34, offsetZ: 164 },
  MAGYAR: { offsetX: -264, offsetZ: 68 },
  MAKO: { offsetX: -218, offsetZ: 184 },
  MICHELANGELO: { offsetX: -182, offsetZ: 36 },
  MICHONNE: { offsetX: -122, offsetZ: 148 },
  MIRAGE: { offsetX: -132, offsetZ: 90 },
  MORDEX: { offsetX: -258, offsetZ: 222 },
  MUNIN: { offsetX: -126, offsetZ: 70 },
  NEGAN: { offsetX: 100, offsetZ: 14 },
  NIMUE: { offsetX: -36, offsetZ: -74 },
  NIX: { offsetX: -268, offsetZ: 190 },
  ONYX: { offsetX: -290, offsetZ: 240 },
  ORION: { offsetX: -182, offsetZ: 112 },
  ORION_PRIME: { offsetX: -142, offsetZ: -30 },
  PEARL: { offsetX: 30, offsetZ: -98 },
  PETRA: { offsetX: -248, offsetZ: 190 },
  PLAGUE_KNIGHT: { offsetX: -75, offsetZ: 46 },
  PO: { offsetX: 130, offsetZ: 18 },
  PRINCESS_BUBBLEGUM: { offsetX: 68, offsetZ: -58 },
  QUEEN_NAI: { offsetX: 26, offsetZ: 284 },
  RAGNIR: { offsetX: -156, offsetZ: 144 },
  RAPHAEL: { offsetX: 78, offsetZ: 0 },
  RAYMAN: { offsetX: -92, offsetZ: 130 },
  RED_RAPTOR: { offsetX: 0, offsetZ: 0 },
  RENO: { offsetX: -100, offsetZ: 52 },
  RETRO_REAPER_NIX: { offsetX: -216, offsetZ: 132 },
  RICK: { offsetX: -6, offsetZ: 36 },
  ROMAN_REIGNS: { offsetX: -241, offsetZ: 270 },
  RYU: { offsetX: -72, offsetZ: 36 },
  SAKURA: { offsetX: -32, offsetZ: 28 },
  SCARLET: { offsetX: -54, offsetZ: 84 },
  SENTINEL: { offsetX: -96, offsetZ: 54 },
  SHIN_SEKAI_KOJI: { offsetX: -10, offsetZ: 54 },
  SHOVEL_KNIGHT: { offsetX: -74, offsetZ: -144 },
  SIDRA: { offsetX: -113, offsetZ: 113 },
  SIMON_BELMONT: { offsetX: -70, offsetZ: 54 },
  SIR_ROLAND: { offsetX: -98, offsetZ: 104 },
  SNAKE_EYES: { offsetX: 14, offsetZ: 78 },
  SOULBOUND_DIANA: { offsetX: -104, offsetZ: 58 },
  STEVONNIE: { offsetX: -150, offsetZ: 132 },
  STORM_SHADOW: { offsetX: -58, offsetZ: 82 },
  SPECTER_KNIGHT: { offsetX: -72, offsetZ: 118 },
  SURVIVOR_LARA_CROFT: { offsetX: 38, offsetZ: -130 },
  TAI_LUNG: { offsetX: -194, offsetZ: 84 },
  TEROS: { offsetX: -79, offsetZ: 125 },
  TEZCA: { offsetX: -194, offsetZ: 150 },
  THATCH: { offsetX: -108, offsetZ: 92 },
  THE_ARBITER: { offsetX: 0, offsetZ: 0 },
  THE_MASTER_CHIEF: { offsetX: 0, offsetZ: 0 },
  THE_ROCK: { offsetX: -48, offsetZ: 72 },
  THE_UNDERTAKER: { offsetX: -104, offsetZ: 4 },
  THEA: { offsetX: 0, offsetZ: 0 },
  THOR: { offsetX: -32, offsetZ: 10 },
  TIGRESS: { offsetX: 0, offsetZ: 244 },
  TOPH: { offsetX: -106, offsetZ: 242 },
  ULGRIM: { offsetX: 0, offsetZ: 48 },
  VAL: { offsetX: -42, offsetZ: 194 },
  VECTOR: { offsetX: 0, offsetZ: 0 },
  VOLKOV: { offsetX: -12, offsetZ: 40 },
  WU_SHANG: { offsetX: 72, offsetZ: 0 },
  XAVIER_WOODS: { offsetX: 0, offsetZ: -98 },
  XULL: { offsetX: 0, offsetZ: 56 },
  YUMIKO: { offsetX: -242, offsetZ: 264 },
  ZARIEL: { offsetX: -90, offsetZ: 58 },
  ZUKO: { offsetX: 40, offsetZ: 150 },
};

export function getCountryFlag(country?: string) {
  if (!country) {
    country = "UNKNOWN";
  }
  return `https://static.brawltools.com/flags/____${country
    ?.toLowerCase()
    .replace(/ /g, "-")}.png`;
}

export function getLegendHead(legend?: string) {
  if (!legend) {
    legend = "UNKNOWN";
  }
  return `https://static.brawltools.com/heads/` + `${legend}.png`;
}

export function getLegendFull(legend?: string) {
  if (!legend) {
    legend = "UNKNOWN";
  }
  return `https://static.brawltools.com/legends/` + `${legend}.png`;
}

export function getLegendOffset(legend?: string, prefix = "") {
  const offset = LEGEND_RENDER_OFFSETS[legend] || { offsetX: 0, offsetZ: 0 };
  if (!prefix) return offset;
  return {
    [`${prefix}.offsetX`]: offset.offsetX,
    [`${prefix}.offsetZ`]: offset.offsetZ,
  };
}

export function getLegendSplash(legend?: string) {
  if (!legend) {
    legend = "UNKNOWN";
  }
  return `${OUTPUT_PATH}/splash/${legend}.png`;
}

export function getLegendName(legend?: string) {
  return LEGEND_NAMES[legend]?.name || "";
}

export const BRACKET_ROUND_MAP: {
  [type in PhaseGroupType]: { [round: number]: string };
} = {
  [PhaseGroupType.T4_PROG]: {
    1: "Final",
    2: "Grand Final",
    [-3]: "Semi-Final",
    [-4]: "Final",
  },
  [PhaseGroupType.T8_PROG]: {
    1: "Semi-Final",
    2: "Final",
    3: "Grand Final",
    [-3]: "Top 8",
    [-4]: "Quarter-Final",
    [-5]: "Semi-Final",
    [-6]: "Final",
  },
  [PhaseGroupType.T16_INV]: {
    1: "Top 16",
    2: "Quarter-Final",
    3: "Semi-Final",
    4: "Final",
    5: "Grand Final",
    [-3]: "Top 16",
    [-4]: "Top 12",
    [-5]: "Top 8",
    [-6]: "Quarter-Final",
    [-7]: "Semi-Final",
    [-8]: "Final",
  },
  [PhaseGroupType.T32_PROG]: {
    1: "Top 32",
    2: "Top 12",
    [-3]: "Top 32",
    [-4]: "Top 24",
    [-5]: "Top 16",
    [-6]: "Top 12",
  },
  [PhaseGroupType.T32_INV]: {
    1: "Top 32",
    2: "Top 24",
    3: "Top 12",
    4: "Semi-Final",
    5: "Final",
    6: "Grand Final",
    [-3]: "Top 32",
    [-4]: "Top 24",
    [-5]: "Top 16",
    [-6]: "Top 12",
    [-7]: "Top 8",
    [-8]: "Quarter-Final",
    [-9]: "Semi-Final",
    [-10]: "Final",
  },
};
